## **Author : Priyesh Yadav** <br>
[Linkedin](https://www.linkedin.com/in/priyeshyadav26) [Github](https://github.com/priyeshyadav/)

# **1. Defining Problem Statement and Analysing basic metrics**

**Problem Statement**<br>
As a Data analyst/ scientist at Netflix, I have been assigned the task of analyzing the given dataset to extract valuable insights and provide actionable recommendations.<br>
It will help Netflix decide which type of shows/movies to produce and how to grow the business.

**Analysing Basic Metrics**<br>
Here we will upload the dataset & run basic commands on data like head(), info(), describe() & shape This is expected to help us in getting a small understaning about type & variation in data.

Lets import the required liberaries.

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Lets see that out CSV has imported succesasfully & we are able to read the data in a pandas data frame.

In [59]:
netflix_data = pd.read_csv("/content/netflix_titles.csv")
netflix_data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Lets verify the shape of the data, this will give us how many rows & columns we have in the dataset, as with previous command of head, we had only see the first 5 rows of the dataset.

In [60]:
netflix_data.shape

(8807, 12)

lets see further information about the data, such as what is the colum type, Not null count (NaN will be considered as Null), output of the infor will help us to get further action points such as converting Dtype of column, Adding/replacing missing values.

In [61]:
netflix_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

Action item that are identified now.


1.   Column with missing values : director, country, date_added, rating, duration & cast.
2.   column where Dtype change would be required : date_added, duration.

Lets see details regaring numarical column, as of now we only have **release_year** as int64 datatype.

In [62]:
netflix_data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

Important thing that we can observe here-<br>
**MIN:1925<br>
MAX:2021**

lets check unique value in each column/attribute as well.

In [63]:
netflix_data.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

# **2. Observations on the shape of data, data types of all the attributes, conversion of categorical attributes to 'category' (If required), missing value detection, statistical summary**

Lets first handle the null values.<br>
director: Replace NaN with 'Unknown Director'<br>
country: Replace NaN with 'Unknown Country'<br>
date_added: Yet to Decide<br>
rating: Replace NaN with 'Unknown Rating'<br>
duration : Replace NaN with '0 min', Explanation for this is available in repective section.<br>

lets analyse **director** column.

In [64]:
netflix_data["director"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: director
Non-Null Count  Dtype
--------------  -----
6173 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [65]:
print(f"Misisng value count is :",netflix_data["director"].isna().sum())

Misisng value count is : 2634

In [66]:
print(f"Non Missing value count is :",netflix_data["director"].notna().sum())

Non Missing value count is : 6173

lets create a function that we can use in furtuer steps to check if missing & non misisng counts are summing upto total counts.

In [67]:
def sum_check(a,b,c):
  if c == a +b:
    print("Sum Match")
  else:
    print("Sum Mismatch")

In [68]:
sum_check(netflix_data["director"].isna().sum(),netflix_data["director"].notna().sum(),netflix_data.shape[0])

Sum Match

Lets fill the NaN with "Unknown Director"

In [69]:
netflix_data['director'] = netflix_data['director'].fillna('Unknown Director')
print(f"Non Missing value count is :",netflix_data["director"].notna().sum())

Non Missing value count is : 8807

Lets analyse **country** column.

In [70]:
netflix_data["country"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: country
Non-Null Count  Dtype
--------------  -----
7976 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [71]:
sum_check(netflix_data["country"].isna().sum(),netflix_data["country"].notna().sum(),netflix_data.shape[0])

Sum Match

In [72]:
netflix_data['country'] = netflix_data['country'].fillna('Unknown Country')
print(f"Non Missing value count is :",netflix_data["country"].notna().sum())

Non Missing value count is : 8807

Lets analyse **rating** column.

In [73]:
netflix_data['rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: rating
Non-Null Count  Dtype
--------------  -----
8803 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [74]:
sum_check(netflix_data["rating"].isna().sum(),netflix_data["rating"].notna().sum(),netflix_data.shape[0])

Sum Match

In [75]:
netflix_data['rating'] = netflix_data['rating'].fillna('Unknown Rating')
print(f"Non Missing value count is :",netflix_data["rating"].notna().sum())

Non Missing value count is : 8807

lets analyse **Cast** column.<br> There will be further update to this column as this contains comma saperated value but as of now, lets populate 'Unknown Cast' for NaN values.

In [76]:
netflix_data['cast'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: cast
Non-Null Count  Dtype
--------------  -----
7982 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [77]:
sum_check(netflix_data["cast"].isna().sum(),netflix_data["cast"].notna().sum(),netflix_data.shape[0])

Sum Match

In [78]:
netflix_data['cast'] = netflix_data['cast'].fillna('Unknown Cast')
print(f"Non Missing value count is :",netflix_data["cast"].notna().sum())

Non Missing value count is : 8807

Lets analyse **Duration** column. <br>
Lets see the column values and decide what we want to update in the misisng values column.

In [79]:
netflix_data['duration'].value_counts()

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
97 min        146
             ...
228 min         1
18 min          1
205 min         1
201 min         1
191 min         1
Name: count, Length: 220, dtype: int64

Seems **duration** has two kind of variations, One which has Season & other have min. Upon seeing the head() once agian , It seems dependent on **TYPE**, So lets do value counts with type to get further understanding.

In [80]:
netflix_data[['type','duration']].value_counts()

type     duration
TV Show  1 Season      1793
         2 Seasons      425
         3 Seasons      199
Movie    90 min         152
         93 min         146
                       ...
         228 min          1
         230 min          1
         8 min            1
         9 min            1
TV Show  17 Seasons       1
Name: count, Length: 220, dtype: int64

So for, <br>type = TV shows, we have season in duration.<br>type=Movie we have XX min.<br> so lets do following things unless we do any mathematical opertion on duration column.<br>Lets add 0 season for TV shows and 0 min for movie where ever we have NaN values.<br>
lets also see how many NaN values we have in each category.

In [81]:
netflix_data.groupby('type')['duration'].apply(lambda x: x.isna().sum())

type
Movie      3
TV Show    0
Name: duration, dtype: int64

Since only type=Movie has NaN value, lets replace them with 0 min, without worrying about the type= TV shows now.

In [82]:
netflix_data['duration'] = netflix_data['duration'].fillna('0 min')
print(f"Non Missing value count is :",netflix_data["duration"].notna().sum())

Non Missing value count is : 8807

Lets analyse **date_added** column.
Lets see the column values and decide what we want to update in the misisng values column.

In [83]:
netflix_data['date_added'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: date_added
Non-Null Count  Dtype
--------------  -----
8797 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [84]:
sum_check(netflix_data["date_added"].isna().sum(),netflix_data["date_added"].notna().sum(),netflix_data.shape[0])

Sum Match

Now there are 2 things that we need to perform.<br>
1. Convert that data type to date, currently its Object. On performing this operation NaN value will change to NaT (Not a Time).<br>
2. New Nat value should be updated to most used dates, We are avoiding to use 'Unknown Date' or 0 as we are converting this column to datetime from object. Another option is to convert this NaT to a very old date but that could become outliers.

Lets check the format of the Date so that we can put it as a keyword argument.

In [85]:
netflix_data['date_added'].head()

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
Name: date_added, dtype: object

In [86]:
netflix_data['date_added'] = netflix_data['date_added'].str.strip()
#We need to strip leading & trailing spaces as we are getting error in date format while converting it.

In [87]:
netflix_data['date_added'] = pd.to_datetime(netflix_data['date_added'], format='%B %d, %Y')

In [88]:
netflix_data['date_added'] = netflix_data['date_added'].fillna(netflix_data['date_added'].mode()[0])
#mode() might result in a series if there are ties, hence we are using the most frequent date

In [89]:
print(f"Not missing values are : ",netflix_data["date_added"].notna().sum())

Not missing values are :  8807

Seems we have concluded **Missing Values Activity**, Lets check our data for missing values.

In [90]:
netflix_data.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [91]:
netflix_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8807 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8807 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

We have observed that we have ***multiple comma separated value in cast column***, Lets **un-nest** it now.<br>
Approach<br>
1. Split the cast column by comma.<br>
2. explode the case column.<br>
3. Strip the cast column.<br>

In [92]:
netflix_data['cast'].head()

0                                         Unknown Cast
1    Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2    Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                         Unknown Cast
4    Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
Name: cast, dtype: object

In [93]:
netflix_data['cast'] = netflix_data['cast'].str.split(',')

In [94]:
netflix_data['cast'].head()
#if we observe, now we have list available in the cast column.

0                                       [Unknown Cast]
1    [Ama Qamata,  Khosi Ngema,  Gail Mabalane,  Th...
2    [Sami Bouajila,  Tracy Gotoas,  Samuel Jouy,  ...
3                                       [Unknown Cast]
4    [Mayur More,  Jitendra Kumar,  Ranjan Raj,  Al...
Name: cast, dtype: object

In [95]:
#Shape before explode
netflix_data.shape

(8807, 12)

In [96]:
#explaoding dataframe on cast & storing it in a new data frame So that we keep both data frames.
netflix_data_exploded = netflix_data.explode('cast')

In [97]:
#Shape after explode
print(f"Shape of original data frame is ",netflix_data.shape)
print(f"Shape of exploded data frame is ",netflix_data_exploded.shape)

Shape of original data frame is  (8807, 12)
Shape of exploded data frame is  (64951, 12)

In [98]:
#strip the additional space in new data frame
netflix_data_exploded['cast'] = netflix_data_exploded['cast'].str.strip()

Lets verify our dataframe once again , that now its free of NaN values and properly exploded on cast.

In [99]:
netflix_data_exploded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64951 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       64951 non-null  object
 1   type          64951 non-null  object
 2   title         64951 non-null  object
 3   director      64951 non-null  object
 4   cast          64951 non-null  object
 5   country       64951 non-null  object
 6   date_added    64951 non-null  datetime64[ns]
 7   release_year  64951 non-null  int64
 8   rating        64951 non-null  object
 9   duration      64951 non-null  object
 10  listed_in     64951 non-null  object
 11  description   64951 non-null  object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 6.4+ MB

# **3. Non-Graphical Analysis: Value counts and unique attributes**

lets create a function which will give us value_counts & nunique.

In [100]:
def attribute_details(column_name):
  # print("Fetching details from netflix_data data frame")
  # print(f"  {column_name} : ")
  # print(f"    The values_counts are {netflix_data[column_name].value_counts()}")
  # print(f"    The unique values are {netflix_data[column_name].nunique()}")
  print("Fetching details from netflix_data_exploded data frame")
  print(f"    The values_counts are {netflix_data_exploded[column_name].value_counts()}")
  print(f"    The unique values are {netflix_data[column_name].nunique()}")
  print("--------------------------------------------")

In [101]:
netflix_data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [102]:
first_lst = ['type','director','country','release_year','rating','duration','release_year']
for column_name in first_lst:
  attribute_details(column_name)
# we are purposefuly ignoring show_id, title, listed_in, description.

Fetching details from netflix_data_exploded data frame
    The values_counts are type
Movie      44950
TV Show    20001
Name: count, dtype: int64
    The unique values are 2
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are director
Unknown Director             19013
Martin Scorsese                139
Cathy Garcia-Molina            125
Steven Spielberg               121
Rajiv Chilaka                  121
                             ...
Anand Kamalakar                  1
Jay Karas, Demetri Martin        1
Tiffanie Hsu                     1
Marina Zenovich                  1
Robert Moresco                   1
Name: count, Length: 4529, dtype: int64
    The unique values are 4529
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are country
United States                    19929
India                             7246
Unknown Country                   5053
Japan                             2751
United Kingdom                    2126
                                 ...
Germany, Italy                       1
United States,                       1
Egypt, Denmark, Germany              1
United Kingdom, Canada, Japan        1
United States, Venezuela             1
Name: count, Length: 749, dtype: int64
    The unique values are 749
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are release_year
2018    7708
2019    7487
2020    7014
2017    6745
2016    5910
        ...
1942       3
1944       3
1946       2
1947       2
1925       1
Name: count, Length: 74, dtype: int64
    The unique values are 74
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are rating
TV-MA             22874
TV-14             15225
R                  7579
TV-PG              4989
PG-13              4810
PG                 2791
TV-Y7              2726
TV-Y               1835
TV-G               1092
NR                  479
G                   427
Unknown Rating       38
NC-17                29
TV-Y7-FV             29
UR                   25
66 min                1
74 min                1
84 min                1
Name: count, dtype: int64
    The unique values are 18
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are duration
1 Season     12284
2 Seasons     3532
3 Seasons     1706
94 min        1255
97 min        1159
             ...
8 min            1
5 min            1
9 min            1
3 min            1
16 min           1
Name: count, Length: 221, dtype: int64
    The unique values are 221
--------------------------------------------
Fetching details from netflix_data_exploded data frame
    The values_counts are release_year
2018    7708
2019    7487
2020    7014
2017    6745
2016    5910
        ...
1942       3
1944       3
1946       2
1947       2
1925       1
Name: count, Length: 74, dtype: int64
    The unique values are 74
--------------------------------------------

Lets list the observation.<br>
1. Direction column also has comma separated values. This should be exploded into netflix_data_exploded data frame.<br>
2. Rating column has duration like data e.g. ['66 min','74 min','84 min'] which need to be converted into 'Unknown Rating' & seems this values needs to be copied into Duration column.
3. Country colum also has comma separated values, This should be exploded into metflix_data_exploded data frame.<br>
4. Duration column related to movie can be converted to int by eleiminating 'min' word.

Lets first update the **Director** column.

In [103]:
print(f"Rows before explode are ",netflix_data_exploded.shape[0])
netflix_data_exploded['director'] = netflix_data_exploded['director'].str.split(',')
netflix_data_exploded = netflix_data_exploded.explode('director')
netflix_data_exploded['director'] = netflix_data_exploded['director'].str.strip()
print(f"Rows after explode are ",netflix_data_exploded.shape[0])

Rows before explode are  64951
Rows after explode are  70812

Lets analyse rows where rating contains wrong data

In [104]:
netflix_data[netflix_data['rating'].str.contains('min')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,[Louis C.K.],United States,2017-04-04,2017,74 min,0 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,[Louis C.K.],United States,2016-09-16,2010,84 min,0 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,[Louis C.K.],United States,2016-08-15,2015,66 min,0 min,Movies,The comic puts his trademark hilarious/thought...

Seems we should copy values from rating to duration & make the rating as 'Unknown Rating'

In [105]:
netflix_data.loc[netflix_data['rating'].str.contains('min'),'duration'] = netflix_data['rating']

In [106]:
netflix_data[netflix_data['rating'].str.contains('min')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,[Louis C.K.],United States,2017-04-04,2017,74 min,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,[Louis C.K.],United States,2016-09-16,2010,84 min,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,[Louis C.K.],United States,2016-08-15,2015,66 min,66 min,Movies,The comic puts his trademark hilarious/thought...

In [107]:
netflix_data.loc[netflix_data['rating'].str.contains('min'), 'rating'] = 'Unknown Rating'
#Once the duration is copied, we are making this rating column value as 'Unknown Rating'

In [108]:
netflix_data[netflix_data['rating'].str.contains('min')]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [109]:
netflix_data['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'Unknown Rating', 'NR', 'TV-Y7-FV', 'UR'],
      dtype=object)

Lets perform the same operation in netflix_data_exploded

In [110]:
netflix_data_exploded[netflix_data_exploded['rating'].str.contains('min')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,0 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2016-09-16,2010,84 min,0 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2016-08-15,2015,66 min,0 min,Movies,The comic puts his trademark hilarious/thought...

In [111]:
netflix_data_exploded = netflix_data_exploded.reset_index(drop=True)
netflix_data_exploded.loc[netflix_data_exploded['rating'].str.contains('min'), 'duration'] = netflix_data_exploded['rating']
netflix_data_exploded.loc[netflix_data_exploded['rating'].str.contains('min'), 'rating'] = 'Unknown Rating'
netflix_data_exploded['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'Unknown Rating', 'NR', 'TV-Y7-FV', 'UR'],
      dtype=object)

Lets update **country** column.

In [112]:
print(f"Rows before explode are ",netflix_data_exploded.shape[0])
netflix_data_exploded['country'] = netflix_data_exploded['country'].str.split(',')
netflix_data_exploded = netflix_data_exploded.explode('country')
netflix_data_exploded['country'] = netflix_data_exploded['country'].str.strip()
print(f"Rows after explode are ",netflix_data_exploded.shape[0])

Rows before explode are  70812
Rows after explode are  89415

Lets update the duration column, where ever type=movie & remove 'min' word from duration & extract the interger part.